nuagenetworks/vis-graphs

Graphs/Table/index.js

@natabal 
Please check this related to Right Menu issue.

[Bug] - Fixed openContext exception #686

---

Graphs/ChordGraph/index.js

@natabal @sreddy80
Fixed issue [stack exception](https://github.com/nuagenetworks/visualization-framework/issues/684).
Please have a look and let me know.

[bug]: Fix stack exception on Flow Analytics #684

---

utils/helpers/icons.js

Added default icon names

---

utils/helpers/icons.js

@natabal @ronakmshah 
Please merge this branch ASAP. It is a roadblock error. Thanks

[Bug]: Fix null object issue

---

Graphs/Table/index.js

@ronakmshah Context switching issue for "Time Interval" fixed.
But for paging and dynamic searching - I need some time to get it done. It is a bit tricky to implement.

(bug): Scroll table - context issue 24 hrs

---

Graphs/GeoMap/index.js

@natabal Please check and approve

Updated info window

---

Graphs/Table/index.js

@natabal 
First, two items have been fixed. 
Regarding the last one, i.e. search bar textbox issue, that was due to multiple version of the React i.e. our VSD framework is using 15.4.0, while React-Filter-Box is using minimum 15.5.x, and therefore creating the issues.
Can't we update the version of VSD framework to 15.6.0, which we currently using for visualizations as well? I believe it will not be going to break anything.
The corresponding PR for the same is: https://github.com/nuagenetworks/visualization-framework/pull/719

[bug]: fix row selection

---

Graphs/Table/index.js

@ronakmshah @bmukheja @natabal 
Set per page size from table configuration instead of ES query in order to optimize performance.

Set page size from configuration and indentation

---

Graphs/AbstractGraph.js
Graphs/GeoMap/index.js
Graphs/HeatmapGraph/index.js

@natabal 
Add unique key generate static method.
Changes required for given PR:-
https://github.com/nuagenetworks/visualization-framework/pull/677
Please review.

[feature]: add graph key generate method

---

Graphs/ChordGraph/default.config.js
Graphs/ChordGraph/index.js

@bmukheja 
Fixed the issue for overflow of graph label. Please have a look.

[bug]: fix label hiddden issue

---

Graphs/AreaGraph/index.js
Graphs/DynamicBarGraph/index.js
Graphs/GeoMap/index.js
Graphs/HeatmapGraph/index.js
Graphs/LineGraph/index.js
Graphs/PieGraph/index.js
Graphs/SimpleTextGraph/index.js
Graphs/style.css
utils/helpers/nest/nestMinMaxSum.js

@natabal 
Remove warnings from graphs and add style to rendering the content in the center. Please have a look.

Remove warnings

---

README.md
utils/helpers/constants.js

@natabal 
Fix related to the issue [Upgrade packages to fix the vulnerability issue #733](https://github.com/nuagenetworks/visualization-framework/issues/733). Please have a look.

[fix]: security vulnerabilities dependencies.

---

Graphs/HeatmapGraph/index.js

@natabal 
Fixed heatmap row [issue](https://github.com/nuagenetworks/visualization-framework/issues/721) on scrolling.

[bug]: heatmap rows are not displayed properly #721

---

Graphs/GeoMap/index.js

@bmukheja Please check it now!

Adding delay

---

Graphs/Table/index.js
SearchBar/index.css

@natabal 
Related to the [commit](https://github.com/nuagenetworks/vsd-react-ui/pull/1576/commits/fa0db7d7f44f8c5e11f27123e47032a0a4ae870e).
Fix table column drop-down filter issue by making it generic and fix search box style.

Fix: search-box css and column selection issue

---

Graphs/SimpleTextGraph/default.config.js
Graphs/SimpleTextGraph/index.js

@natabal 
Fix label alignment and formatting content.

[bug]: fix label css and formatting

---

Graphs/Table/index.js
InfoBox/index.js
InfoBox/styles.js

@natabal 
Move infobox from [visualization](https://github.com/nuagenetworks/visualization-framework) into vis-graph.

[feature]: add infobox

---

Graphs/GeoMap/index.js
Graphs/PieGraph/index.js
utils/helpers/filterEmptyData.js

Field called "showZero" can be used.

Option to Show Zero values on piegraph

---

Graphs/MultiColumnStatusTextGraph/index.js
Graphs/MultiColumnStatusTextGraph/style.css
Graphs/SimpleTextGraph/index.js
Graphs/index.js

Multi-Column color coded status graph

---

Graphs/AbstractGraph.js
Graphs/GeoMap/index.js
Graphs/Table/index.js
Graphs/style.css
README.md
SearchBar/AutoCompleteHandler.js
SearchBar/index.css
SearchBar/index.js

Fixed the following errors:- 
1) [Remove sorting from label columns](https://github.com/nuagenetworks/visualization-framework/issues/763).
2) [Default view is not covering all the NSGs in Geo Map display when NSG's are placed across the world](https://github.com/nuagenetworks/visualization-framework/issues/765).
3) [Filter box functionality](https://github.com/nuagenetworks/visualization-framework/issues/762)
- Blank window with no search on "selection" search column in geomap/table - **Fixed**
- Delete button not working on the search filter box - Actually that was not a delete button, it is only for valid and invalid search string, so I have changed icons to get rid of confusion.  **[See 3rd](https://nhabuiduc.github.io/)** 
- When deleting with backspace, data shows …

[bug]: fixed filters box functionality and default map view

---

Graphs/Table/tableGraph.test.js
Graphs/testHelper.js

@nxanil Please Review time format related changes in tableGraph

timeformat related changes in tableGraph

---

Graphs/DynamicBarGraph/barGraph.test.js
Graphs/DynamicBarGraph/mock/configurations/verticalNumber.json
Graphs/HeatmapGraph/heatmapGraph.test.js
Graphs/HeatmapGraph/mock/configurations/withoutBrush.json
Graphs/PieGraph/mock/configurations/withoutOtherOption.json
Graphs/PieGraph/pieGraph.test.js
Graphs/SimpleTextGraph/mock/configurations/withoutTitle.json
Graphs/SimpleTextGraph/simpleTextGraph.test.js
Graphs/Table/mock/configurations/pagination.json
Graphs/Table/tableGraph.test.js
Graphs/VariationTextGraph/mock/configurations/configuration.json
Graphs/VariationTextGraph/variationTextGraph.test.js

@nxanil Please look into this.

Click Event For BarGraph

---

Graphs/Table/tableGraph.test.js

@nxanil  please review this PR.

table graph test click event issue fix

---

Graphs/style.css

@natabal 
Change the font size of the graph messages.

Change message font size

---

Graphs/HeatmapGraph/default.config.js
Graphs/defaultProperties.js

@natabal Please review and merge.

Moved the other colors to all common area.

---

Graphs/ChordGraph/index.js

@natabal 
Fixed color issue of the chord graph. Please have a look

[bug]: fix color scheme for chord graph

---

Graphs/Table/index.js
Graphs/Table/tooltipStyle.js
Graphs/VariationTextGraph/index.js
README.md

@natabal 
Fix table tooltip copy icon and variationTextGraph up/down icon issue. Please have a look.

[css]: fix table tooltip and text graph icon issue

---

README.md

@natabal 
Add tabifyOptions in the readme. Please have a look.
Reference PRs - https://github.com/nuagenetworks/visualization-framework/pull/782 and https://github.com/nuagenetworks/js-bambou/pull/70

Add custom tabify docs

---

Graphs/Table/index.js
utils/helpers/ESSearchConverter.js

@natabal 
Fix given issue: https://github.com/nuagenetworks/vsd-react-ui/issues/1860
Please have a look and let me know.

[bug]: fix change time interval issue

---

README.md
utils/helpers/ESSearchConverter.js

@natabal Please review for ES based Search on nested columns, must work for most of the cases.

[feature]: add nested query option on elasticsearch

---

Graphs/Table/index.js
Graphs/VariationTextGraph/index.js
SearchBar/index.js

Updated usage of icons to match newest `react-icons` package version.

CRA Upgrade

---

Graphs/AbstractGraph.js
Graphs/DynamicBarGraph/index.js
Graphs/GeoMap/index.js
Graphs/LineGraph/index.js
Graphs/PieGraph/index.js
Graphs/SimpleTextGraph/index.js
SearchBar/index.js

@nxanil  @natabal 
Please review this PR. i have added id and classes for testing purposes.

add ids and class for testing

---

Graphs/GeoMap/index.js

geoGraph className issue

---

Graphs/MultiColumnStatusTextGraph/index.js
Graphs/PortGraph/default.config.js
Graphs/PortGraph/index.js
Graphs/PortGraph/styles.js
Graphs/SimpleTextGraph/index.js
Graphs/index.js
Graphs/style.css
README.md
sample/portGraph/configuration.json
sample/portGraph/data.json

@natabal Please have a look at the PortGraph component.

feature: port graph component

---

utils/columnAccessor.js

@natabal 
Fixed given issue #78  - 
[![Screenshot from Gyazo](https://gyazo.com/11fbb51076948a60923ef3faa7bf63b3/raw)](https://gyazo.com/11fbb51076948a60923ef3faa7bf63b3)

[bug]: show column value which contain dots

---

Graphs/AbstractGraph.js
Graphs/PieGraph/index.js
Graphs/style.css
README.md

@natabal 
Scrollable legend for Pie Graph has been implemented. Please review.

PieGraph: Add scrollable legend

---

Graphs/Table/index.js

@natabal fix issue #94. Please have a look

Fix hide pagination issue

---

Graphs/DynamicBarGraph/index.js

@natabal 
Fix issue - https://github.com/nuagenetworks/vsd-react-ui/issues/1986.

[bug]: handle invalid data

---

Graphs/AbstractGraph.js
Graphs/GeoMap/index.js
Graphs/PortGraph/index.js
Graphs/PortGraph/styles.js
README.md
utils/helpers/icons.js

@natabal 
Make changes corresponding the issue - https://github.com/nuagenetworks/vsd-react-ui/issues/2052
Please have a look and let me know.

Add option to make svg icon configurable

---

Graphs/LineGraph/index.js

@natabal 
Add x-axis label orientation for Line Graph. Please have a look.

[feature]: add x-axis orientation for LineGraph

---

Graphs/HeatmapGraph/index.js

@natabal 
Fix issue https://github.com/nuagenetworks/visualization-framework/issues/674
Please have a look

fix heatmap cell alignment issue

---

Graphs/LineGraph/index.js
README.md

@natabal 
Please review the PR for "line graph supporting text for yAxis".
I have updated the docs as well.

Add custom label option

---

Graphs/AbstractGraph.js
README.md

@natabal 
Fixed issue #107.
Also, added `labelFontSize` property to configure the font size of legend labels.

[bug]: fix label offset issue

---

Graphs/Table/index.js

@natabal 
Removed default order after ascending sorting. Please have a look.

Remove default order after asc sort

---

Graphs/TreeGraph/default.config.js
Graphs/TreeGraph/index.js
Graphs/TreeGraph/styles.css

In reference to issue : https://github.com/nuagenetworks/vsd-react-ui/issues/1810
Point completed : 
1. On clicking a node not all the data should re-render

Tree graph enhancement

---

Graphs/ChordGraph/index.js

@natabal 
Fix issue to reset chord diagram on a drop-down change. Please have a look.

[bug] fix reset graph issue

---

Graphs/SimpleTextGraph/index.js
Graphs/Table/index.js
Graphs/VariationTextGraph/index.js

@natabal 
Fixed issue #125. Please have a look.
Also, make some minor CSS changes for text graphs.

Fix table sorting on refresh #125

---

Graphs/Table/index.js

@natabal 
Fixed duplicate column [issue](https://github.com/nuagenetworks/vis-graphs/issues/134) of the table.
Note:- Today VSD server is down, so not able to reproduce the same issue on `vsd-react-ui`, therefore, I have generated the same issue by creating dummy data.
Also, please check the sorting [issue](https://github.com/nuagenetworks/vis-graphs/issues/125) on the refresh interval.

[bug]: duplicate column #134

---

Graphs/LineGraph/index.js
README.md

@killanch @natabal
Add feature to manually define the color of each line in Line-graph. Please have a look.
Also, update the docs for the same.

Provide a mechanism to map yKey to color #61

---

Graphs/DynamicBarGraph/index.js

@natabal  @bmukheja 
Fix issue #139. Please have a look.

[bug]: duplicate legend #139

---

Graphs/DynamicBarGraph/index.js

@natabal 
Fix invalid data issue in barGraph. Please have a look.

Fix invalid data issue in barGraph

---

Graphs/ProgressBarGraph/default.config.js
Graphs/ProgressBarGraph/index.js
Graphs/ProgressBarGraph/style.js
Graphs/index.js
README.md
sample/progressBarGraph/configuration.json
sample/progressBarGraph/data.json

@natabal 
Completed progress bar graph. Please have a look (sample images and data).
Sample Data: - 
`
[
{
"label": "Gold",
"maxData": 300000,
"usedData": 168663
},
{
"label": "Silver",
"maxData": 26000,
"usedData": 18803
},
{
"label": "Platium",
"maxData": 3000,
"usedData": 1896
},
{
"label": "Bronze",
"maxData": 20000,
"usedData": 15000
},
{
"label": "Dimond",
"maxData": 2200000,
"usedData": 1896000
}
]
`

[feature]: Progress Bar

---

Graphs/TreeGraph/default.config.js
Graphs/TreeGraph/index.js
Graphs/TreeGraph/styles.css

@natabal please check below all the three points: 
1. Re-rendering issue resolved
2. Tooltip if nodes exceeded more than specified length
3. Show all selected nodes and Pagination

Tree Graph Changes

---

Graphs/ProgressBarGraph/index.js

@natabal 
progressbar have an issue. i have fix that one. Please have a look.

Fix progressbar issue

---

Graphs/AbstractGraph.js
Graphs/AreaGraph/index.js
Graphs/DynamicBarGraph/index.js
Graphs/HeatmapGraph/index.js
Graphs/LineGraph/index.js
Graphs/PieGraph/index.js
Graphs/TreeGraph/index.js
Graphs/XYGraph.js
Graphs/defaultProperties.js

@natabal
Legends have been implemented for BarGraph, LineGrpah, AreaGraph, HeatMap, PieGraph. 

Scrolling feature for legends

---

Graphs/Table/index.js

@natabal 
Fixed select Column issue https://github.com/nuagenetworks/vsd-react-ui/issues/2758. Please have a look.

Table Select column issue

---

Graphs/DynamicBarGraph/index.js
Graphs/VariationTextGraph/index.js

@natabal 
Identify the following issue while testing and fixed them: - 
[![Screenshot from Gyazo](https://gyazo.com/a41eae8872c24d7ac4ba50567afe8614/raw)](https://gyazo.com/a41eae8872c24d7ac4ba50567afe8614)
[![Screenshot from Gyazo](https://gyazo.com/f64fc47758a60f2dc2540bba078aa5a8/raw)](https://gyazo.com/f64fc47758a60f2dc2540bba078aa5a8)
Note: dependent PR - https://github.com/nuagenetworks/vsd-react-ui/pull/2789

[bug]: fix empty data issue

---

Graphs/ChordGraph/index.js

@natabal 
Fix issue https://github.com/nuagenetworks/vsd-react-ui/issues/2782

Fix tooltip data issue for chord graph

---

Graphs/VariationTextGraph/index.js

@natabal  @killanch
Fix issue https://github.com/nuagenetworks/vsd-react-ui/issues/2812. Please have a look.

[Bug] VariationTextGraph issue

---

Graphs/Table/default.config.js
Graphs/Table/index.js
Graphs/Table/style.js
README.md

Fix issue #167. Please have a look.

Fix table header alignment issue #167

---

Graphs/Table/index.js
README.md

Add the option to set the font color of the column. Issue #166 

set font color of the table column #166

---

Graphs/VariationTextGraph/index.js

@natabal  @killanch
Fixed issue:- #177. Please have a look.

[Bug] fix variationText issue #177

---

utils/helpers/stack.js

@natabal 
Fix issue #161. Please have a look.

Fix - bar height alignment  #161

---

Graphs/Table/default.config.js

- fixes the garbled rows issues for now
- columns now aligned with header row

Table: revert fixed header; add tableLayout auto to default config

---

Graphs/PortGraph/index.js

@natabal 
Fix issue #182. Please have a look.

[bug]: width not update #182

---

Graphs/ProgressBarGraph/index.js

ProgressBarGraph - handle no data

---

Graphs/ChordGraph/index.js

- When switching between data and no data in the chord diagram the svg is removed from the dom however this.chordDiagram and this.svg do not get nullified even though the svg is not rendered.
- on updating just the data once the data is filtered it does not get re-rendered - moved this.filterData in state

Switching filters does not update chord diagram accordingly

---

utils/helpers/nest/nestMinMaxSum.js

@natabal  @killanch
Fix issue #194. Please have a look.

[fix] barGraph - height issue #194

---

Graphs/AbstractGraph.js

Fix issue #191. Please have a look.

[fix]: tooltip exception issue #191

---

Graphs/AbstractGraph.js

@natabal 
Fixed Issue https://github.com/nuagenetworks/vsd-react-ui/issues/2049.  Please have a look.

[Bug] fix jumping tooltip

---

Graphs/TreeGraph/default.config.js
Graphs/TreeGraph/index.js

Network tree graph pagination

---

Graphs/Table/index.js

@natabal 
Fixed the issue: https://github.com/nuagenetworks/vsd-react-ui/issues/3032. Please have a look.

[Bug]: table select column issue

---

Graphs/Table/index.js
Graphs/Table/style.css
Graphs/Table/tooltipStyle.js

@natabal 
Fix issue #201. Please have a look.

[Bug]: table tooltip issue #201

---

Graphs/AbstractGraph.js
Graphs/AreaGraph/index.js
Graphs/DynamicBarGraph/index.js
Graphs/GeoMap/index.js
Graphs/HeatmapGraph/index.js
Graphs/PortGraph/index.js
Graphs/TreeGraph/index.js
Graphs/VariationTextGraph/index.js
SearchBar/AutoCompleteHandler.js
SearchBar/index.js

Adding tree shaking in graphs module

---

Graphs/XYGraph.js
README.md

@natabal  @killanch 
Issue #209 has been completed. Please have a look.

[Bug]: Accept xTicksLabel from configuration #209

---

Graphs/LineGraph/index.js
README.md

@natabal 
Issue #206 has been fixed. Please have a look.

[Bug] Fix Line graph showing discontinued lines

---

Graphs/Table/index.js

Fix issue # 220. Please have a look.

[bug]: fix issue for re-appearing column on refresh #220

---

utils/helpers/ESSearchConverter.js

@natabal 
Fix Issue: https://github.com/nuagenetworks/vsd-react-ui/issues/3168. Please have a look.

[Bug]: Fix advance filter regex issue

---

README.md

@natabal 
Update docs for excludedColumns key. Please have a look.

[Docs]: update docs for excludedColumns key

---

Graphs/DynamicBarGraph/index.js
Graphs/XYGraph.js

@natabal  @killanch
Fix issue #209. Please have a look.

[Bug]: Fix Accept xTicksLabel from configuration issue

---

Graphs/Table/index.js
SearchBar/index.js

@nxanil This is for the 5.4 branch with minor changes I made. Please have a look.

Table search bar to support manually triggering the search

---

Graphs/ChordGraph/index.js
README.md

@natabal 
Fix issue #221. Please have a look.

[Bug]: Pass listener into chord graph

---

Graphs/Table/index.js

@natabal ,
Fix the table header alignment issue. Please have a look.

[bug]: fix header alignmnet

---

Graphs/TreeGraph/index.js

show tooltip when name/desc is truncated

---

Graphs/DynamicBarGraph/index.js

Fix issue #139. Please have a look.

[Bug]: Fix duplicate legends issue

---

README.md

Fix issue https://github.com/nuagenetworks/js-bambou/issues/126. Please have a look.
Ref PR:- https://github.com/nuagenetworks/js-bambou/pull/131, https://github.com/nuagenetworks/vsd-react-ui/pull/3306

Update doc for support count

---

Graphs/Table/index.js

Fix issue #258. Please have a look
Dependent PR - https://github.com/nuagenetworks/vsd-react-ui/pull/3337

[bug]: table pagination on filter reset

---

utils/columnAccessor.js

[Bug]: Fix invalid tooltio issue in multiline graph

[r5.4] tooltip fix - cherry-pick from 0.0

---

Graphs/SimpleTextGraph/index.js
README.md

cherry-pick of 0.0 commit
Required for http://mvjira.mv.usa.alcatel.com:8080/browse/VSD-38562

[r5.4] SimpleTextGraph bottom title

---

Graphs/Table/index.js
README.md

Reverts nuagenetworks/vis-graphs#216

Revert "[feature]: add dynamic columns"

---

Graphs/Table/index.js
README.md

- Base code from https://github.com/nuagenetworks/vis-graphs/pull/216
- Resolved conflicts
Sample:

Table - dynamic columns

---

Graphs/DynamicBarGraph/index.js
README.md
utils/helpers/barGraph/dataParser.js
utils/helpers/limit/limit.js
utils/helpers/nest/nest.js

Fix issue #282. Please have a look.

[Bug]: Fix BarGraph preserve data order issue

---

Graphs/style.css

fixing css glitch after react upgrade

---

Graphs/PortGraph/index.js
InfoBox/index.js
InfoBox/styles.js
README.md

- InfoBox styling changes and add a x (close button) instead of a button
- support for custom tooltip component.

Port tooltip upgrade

---

Graphs/PortGraph/index.js
InfoBox/index.js
InfoBox/styles.js
README.md

* Port tooltip upgrade, VSD-32168
* Update README, VSD-32168

Port tooltip upgrade (#291)

---

Graphs/LineGraph/index.js

@natabal 
Add zoom feature into lineGraph. Please have a look.

[Feature]: Add brush and zoom into the line graph

---

Graphs/Table/index.js

Fix issue #265 and #298. Please have a look.
Dependent PR : https://github.com/nuagenetworks/vsd-react-ui/pull/3502

[bug]: Show column on row selection

---

Graphs/Table/index.js

@natabal 
Fix issue #297. Please have a look.

[bug]: On refresh row unselected

---

Graphs/GeoMap/index.js
SearchBar/AutoCompleteHandler.js

Fixes below,
1. AutoCompleteHandler exception with lodash/chain - used Set to determine unique values
2. Do not render search bar when geo map is not displayed

VSD-39593 - fix geomap issues

---

Graphs/GeoMap/index.js
SearchBar/AutoCompleteHandler.js

* avoid lodash chain, do not render searchbar if no apikey
* use chain

VSD-39593 - fix geomap issues (cherry-pick from 0.0)

---

Graphs/DynamicBarGraph/index.js
utils/helpers/barGraph/barWidth.js

Fix issue #318. Please have a look.

[Bug]: Fix BarGraph date histogram issue

---

Graphs/DynamicBarGraph/index.js

Fix issue #323. Please have a look.

[Bug]: Fix BarGraph date histogram interval issue

---

Graphs/AbstractGraph.js
Graphs/defaultProperties.js

@natabal 
I have fixed the unnecessary scrollbar in legends. Please have a look.

Fix unnecessary scrollbar in legend

---

Graphs/AbstractGraph.js

Use a function to avoid code duplication to compute the legend line height and adjust the width to '100%' on legend.

legend dimension adjustment

---

Graphs/AbstractGraph.js

Fixed issue https://github.com/nuagenetworks/vsd-react-ui/pull/3272. Please have a look.

[Bug]: Fix Area Graph issue

---

HOC/WithConfigHOC.js
ThemeProvider.js
ThemeStyle.js

@natabal 
Add feature to provide a custom theme to vis-graph. Please have a look.
Dependent PR: [#3759](https://github.com/nuagenetworks/vsd-react-ui/pull/3759).

[Feature]:Graph theme context

---

GraphsV2/PortGraph/index.js
GraphsV2/ProgressBarGraph/index.js
GraphsV2/VariationTextGraph/index.js
GraphsV2/index.js
GraphsV2/utils/helper.js

Added Setting for Unit Test cases

Added Setting for Unit Test cases

---

Graphs/Table/index.js
Graphs/Table/style.css
Graphs/Table/style.js
Graphs/Table/tooltipStyle.js
README.md

@natabal 
We have performed some optimization techniques and refactored the code to improve performance. 

Table: Optimization and refactoring

---

Graphs/Table/index.js

@natabal 
Fixed Issue https://github.com/nuagenetworks/vsd-react-ui/issues/3930. Please have a look.
Ref PR: https://github.com/nuagenetworks/vsd-react-ui/pull/3954

[Bug]: Fix table sort exception

---

Graphs/Table/index.js

@natabal 
Fixed issue #358. Please have a look.

[Bug]: Fix Search bar re-render issue

---

Graphs/Table/index.js

@natabal 
Fixed issue #360. Please have a look.
Dep PR: https://github.com/nuagenetworks/vsd-react-ui/pull/3978

[Bug]:Fix props issue for mui-datatable.

---

Graphs/Table/index.js

@natabal 
Fix Issue #359. Please have a look.

[Bug]: Fix stack exception on object-hash

---

Graphs/LineGraph/index.js

@natabal 
Fixed issue #313. Please have a look.

[Fix]: Line Tooltip issue

---

Graphs/LineGraph/index.js

[Fix]: Multiline Tooltip issue (#365)

---

Graphs/LineGraph/index.js

Fixed #313. Please have a look.

[Fix]: Line Graph Tooltip issue

---

Graphs/MultiColumnStatusTextGraph/index.js
GraphsV2/GaugeChart/index.js
GraphsV2/PieGraph/index.js
GraphsV2/PortGraph/index.js
GraphsV2/ProgressBarGraph/index.js

Fix vis graph issue related `MultiColumnStatusTextGraph` `pieGraph` `progressBarGraph` `guageGraph` `portGraph`

[Bug] fix vis-graph issues

---

GraphsV2/Components/utils/RechartsTooltip.js
GraphsV2/LineGraph/index.js
GraphsV2/utils/DataParser/multiLineParser.js

@natabal 
Fix LineGraph issue. Please check once.

[Bug]: fix lineGraph and tooltip issue

---

GraphsV2/ProgressBarGraph/index.js

@natabal 
Fix ProgressBar Graph NaN issue. Please have a look.
Dep: https://github.com/nuagenetworks/js-bambou/pull/170

[Fix]: ProgressBar Graph NaN issue

---

Graphs/Table/index.js
GraphsV2/Table/index.js
theme/index.js

- Upgrade Table to material UI latest npm package; 
- Add custom toolbar for refreshing the table.
@nxanil Please review this PR. I will want to merge it asap.

Table Fixes

---

GraphsV2/Table/index.js

@natabal 
Fix table Graph issue. Please have a look.

[Fix]: Table Graph issue

---

GraphsV2/AreaGraph/index.js
GraphsV2/Components/utils/RechartsTooltip.js
GraphsV2/LineGraph/index.js
GraphsV2/PieGraph/index.js
GraphsV2/utils/helper.js

@natabal 
Added Percentage in `PieGraph` tooltip. Please have a look.

Add Percentage in PieGraph tooltip

---

GraphsV2/Heatmap/index.js
GraphsV2/utils/DataParser/stackedParser.js

@natabal 
Fixed stacked barGraph & heatmap X ticks issue.

[Fix]: stacked barGraph & heatmap X ticks issue

---

GraphsV2/Heatmap/index.js

@natabal 
Fixed `Heatmap` title and axis position issue. Please have a look.

[Fix]: Heatmap title and axis position issue

---

GraphsV2/NewTable/index.js

Provide a cellRenderer to allow react elements to be displayed as a column; allow styling for column selection;

Styling for select column; add cellRenderer

---

GraphsV2/Table/index.js

Selected rows should be an array

selectedRows re-initialization fix

---

GraphsV2/Table/index.js

@natabal 
Fixed issue #398. Please have a look.

[Fix]: Row Selection data issue

---

Graphs/Table/index.js

@natabal 
Fixed issues #400 and #401. Please have a look.

[Fix]: Table row saved issue

---

Graphs/AbstractGraph.js
Graphs/HeatmapGraph/index.js
Graphs/XYGraph.js
Graphs/utils/DataParser/stackedParser.js
Graphs/utils/helper.js

@natabal 
Fixed issue #403. Please have a look.

[Fix]: Heatmap graph click issue

---

Graphs/Table/index.js

@natabal @sreddy80
Fixed issue #409. Please verify once.
Thanks!

[Fix]: Table missing Horizontal scroll bar

---

Graphs/BarGraph/index.js

@natabal 
Fixed Stacked bar graph tooltip issue. Please have a look.

[Fix]: Stacked bar graph tooltip issue

---

Graphs/TreeGraph/default.config.js
Graphs/TreeGraph/index.js
constants.js

@natabal 
Tree Graph layout changes have been implemented. Please review PR.

[Enhancement]: Tree Graph layout changes

---

Graphs/BarGraph/index.js

- This is a cherry-pick of #411

[Fix]: Stacked bar graph tooltip issue (#411)

---

Graphs/ProgressBarGraph/index.js

VSD-50716 - progress graph data

---

Graphs/Table/index.js

Table - fix exception when column data is object

---

Graphs/Table/index.js

@killanch
Fixed issue #408. Please have a look.

[Fix]: Table tooltip issue

---

Graphs/Table/index.js

VSD-51054 - table tooltips

---

Graphs/LineGraph/index.js
Graphs/utils/DataParser/index.js
Graphs/utils/DataParser/multiLineParser.js
HOC/WithConfigHOC.js

@killanch 
Fixed issue #418. Please have a look.

[Bug]: Fix multiline tooltip issue

---

Graphs/LineGraph/index.js
Graphs/utils/DataParser/index.js
Graphs/utils/DataParser/multiLineParser.js
HOC/WithConfigHOC.js

MultiLineGraph Tooltip Issue

---

Graphs/BarGraph/index.js
Graphs/Components/utils/RechartsTooltip.js

@killanch @preshitg
Fixed issue #423. Please have a look.

[Fix]: Bar Graph tooltip issue

---

Graphs/BarGraph/index.js
Graphs/Components/utils/RechartsTooltip.js

BarGraph Tooltip Issue r20.10

---

Graphs/Table/index.js

@natabal 
Fixed table sort direction issue. Please have a look.

[Bug]: fix table sort direction issue

---

Graphs/Table/index.js

VSD-51234 [Bug]: fix table sort direction issue (#406)

---

Graphs/AbstractGraph.js
Graphs/AreaGraph/default.config.js
Graphs/HeatmapGraph/default.config.js
Graphs/XYGraph.js
Graphs/defaultProperties.js

@killanch @chaitanyahalbe 
Fixed issue #416. Please have a look.
Dep PR:  https://github.com/nuagenetworks/vsd-react-ui/pull/4757
Old Graph:
New Graph:

[Fix]: Heatmap & Area Graph whiteSpace issue

---

Graphs/AbstractGraph.js
Graphs/AreaGraph/default.config.js
Graphs/HeatmapGraph/default.config.js
Graphs/XYGraph.js
Graphs/defaultProperties.js

VSD-50879 Fix whitespaces in heatmap and area graph

---

Graphs/AbstractGraph.js
Graphs/AreaGraph/default.config.js
Graphs/HeatmapGraph/default.config.js
Graphs/XYGraph.js
Graphs/defaultProperties.js

VSD-50879 Heatmap & Area Graph whiteSpace issue

---

Graphs/style.css

VSD-51249 increased legend font size

---

Graphs/AbstractGraph.js
Graphs/AreaGraph/index.js
Graphs/Components/utils/Legend/StandardLegend.js
Graphs/Components/utils/Legend/index.js
Graphs/HeatmapGraph/index.js

Cherry-pick of https://github.com/nuagenetworks/vis-graphs/pull/436

Fix Heatmap and Area Graph legends

---

Graphs/style.css

VSD-51249 increased legend font size - r20.10

---

Graphs/AbstractGraph.js
Graphs/defaultProperties.js

@killanch @chaitanyahalbe @sreddy80
Fixed issue #434. Please check once. This issue happened because of this https://github.com/nuagenetworks/vis-graphs/pull/435

[Fix]: Heatmap graph legend and xAxis ticks issue

---

Graphs/ChordGraph/Svg.js

VSD-51747 onClick error when clicked inside graph area (r20.10)

---

Graphs/AbstractGraph.js
Graphs/defaultProperties.js

VSD-51478 Heatmap graph legend and xAxis ticks issue

---

Graphs/Table/index.js
README.md
SearchBar/AutoCompleteHandler.js
SearchBar/index.js
constants.js
utils/helpers/ESSearchConverter.js

@killanch @chaitanyahalbe 
Added new operator (<=, >=, <, >) for all numeric column value. https://github.com/nuagenetworks/vis-graphs/issues/446.
@chaitanyahalbe 
please add `additionalSearchOperator: ture` in the visualization file where you want to enable this feature.

[Added]: More operator for number value

---

Graphs/Table/index.js
README.md
SearchBar/AutoCompleteHandler.js
constants.js
utils/helpers/ESSearchConverter.js

VSD-51763 [Added]: More operator for number value (#450)

---

Graphs/PieGraph/index.js

fix pie graph tooltip (#452)

---

Graphs/Components/utils/RechartsTooltip.js
Graphs/LineGraph/index.js

@killanch 
Fixed issue https://github.com/nuagenetworks/vis-graphs/issues/454. Please have a look.

VSD-52360 Line graph tooltip issue

---

Graphs/BarGraph/index.js
Graphs/Components/utils/GraphAxis.js
Graphs/Components/utils/xAxis.js
Graphs/utils/formatter/index.js

Added X label translation for bar graphs
To be used in Web Domain Reputation graph

Web Domain Reputation - xTickLabel translation

---

Graphs/BarGraph/index.js
Graphs/Components/utils/GraphAxis.js
Graphs/Components/utils/xAxis.js
Graphs/utils/formatter/index.js

cherry pick of https://github.com/nuagenetworks/vis-graphs/pull/467

Web Domain Reputation - xTickLabel translation - r20.10

---

Graphs/Table/index.js

@myTechPlayArea @preshitg 
Fixed Issue: https://github.com/nuagenetworks/vis-config/issues/247.

Fixed table column issue when switching webfilter.

---

Graphs/Table/index.js

@myTechPlayArea @preshitg 
Update branch r20.10 with PR:https://github.com/nuagenetworks/vis-graphs/pull/469.

Bug/table column web filter r20.10

---

Graphs/Table/index.js

@myTechPlayArea
Added table property for size filter. 
The table first time will load data for the given size and then reload the same amount of data until the given table size is filled.

added table size filter property

---

SearchBar/index.js

Fixed graph resize searchbar.
Please review this PR.

Fixed graph resize issue

---

Graphs/Table/index.js

@myTechPlayArea
Added table property for size filter in branch r20.10.

R20.10/table size filter

---

SearchBar/index.js

Fixed graph resize searchbar. Branch: r20.10

r20.10/resolve graph resize issue

---

Graphs/TreeGraph/index.js

Fixed issue https://github.com/nuagenetworks/vsd-react-ui/issues/5161. Please test and verify.
Ref PR: https://github.com/nuagenetworks/vsd-react-ui/pull/5173

[Fix]: Dashboard Topology slowness issue

---

Graphs/TreeGraph/index.js

cherry pick from https://github.com/nuagenetworks/vis-graphs/pull/477/files

Dashboard Topology slowness issue 0.0

---

Graphs/Table/index.js

cherry pick of https://github.com/nuagenetworks/vis-graphs/pull/478

VSD-55581 - UI crashing on NSG monitoring option-0.0

---

Graphs/AbstractGraph.js
Graphs/HeatmapGraph/default.config.js
Graphs/HeatmapGraph/index.js

Fixed NAT-T Events visualisation have Y axis overlap issue in heatMap graph.
ISSUE:[5297](https://github.com/nuagenetworks/vsd-react-ui/issues/5297)

Fixed heatmap issue

---

Graphs/Table/index.js

Fixed Alarm Table Severity color issue. .[ ISSUE#5296](https://github.com/nuagenetworks/vsd-react-ui/issues/5296)

Fixed Alarm Table Severity color issue.

---

Graphs/Table/index.js

@myTechPlayArea
Fixed NSG Alarm Table Issue. cherry-pick of [PR:485](https://github.com/nuagenetworks/vis-graphs/pull/485)

Fix nsg alarm table issue.

---

Graphs/Table/index.js

@jopidoo 
Fixed VSD GUI truncates information for NSG upgrade monitor  [ISSUE#5300](https://github.com/nuagenetworks/vsd-react-ui/issues/5300).

Fixed NSG monitor view Table issue

---

Graphs/BarGraph/index.js
Graphs/PieGraph/index.js
constants.js

@jopidoo @edwinfeener
Fixed Clickable issue of Top 5 Discovered Application(**Bar Graph**) in branch r20.10 ticket: [VSD-58254](http://mvjira.mv.usa.alcatel.com:8080/browse/VSD-58254)
Please review this PR.

Fixed Bargraph clickable area issue in branch r20.10 ticket: VSD-58254

---

Graphs/Components/utils/yAxis.js
Graphs/LineGraph/index.js

Fix VSD 57649 NSG - LTE uplink connection type and status in VSD-A are numeric

Cheery-pick merge pull request #494 from nuagenetworks/VSD-57649

---

Graphs/Table/index.js

@jopidoo @edwinfeener
Fixed 4001 alarm issue branch master [ticket:VSD-59312](http://mvjira.mv.usa.alcatel.com:8080/browse/VSD-59312).
please review this PR.

Fixed 4001 alarm issue branch master ticket:VSD-59312

---

Graphs/Table/index.js

@jopidoo @edwinfeener
Fixed 4001 alarm issue branch r20.10 [ticket:VSD-59312](http://mvjira.mv.usa.alcatel.com:8080/browse/VSD-59312).
please review this PR.

Fixed 4001 alarm issue branch r20.10 ticket:VSD-59312
