nuagenetworks/vis-graphs

Graphs/GeoMap/index.js
Graphs/Table/index.js
README.md

Fix the following issues:
1) [NSG the icon will disappear]( https://github.com/nuagenetworks/visualization-framework/issues/773)
2) [Sorting based on NSG Version column is not working on NSG table in Map View](https://github.com/nuagenetworks/visualization-framework/issues/774)
3) Update docs for required packages

[bug]: fix sorting and clustering issue

---

Graphs/Table/index.js
README.md

We are already making the filter from columns array in the configuration file.
Just added a feature to hide the filter from search bar i.e `"filter": false`.
You may also set `"selection": true` to enable autocompleter on any column.
Note: docs updated for reference. 
Please let me know if this will not work for you.

[add]: functionality to add/remove column for filter (search bar)

---

Graphs/SimpleTextGraph/default.config.js
Graphs/SimpleTextGraph/index.js
Graphs/Table/index.js
Graphs/Table/style.js
SearchBar/index.js

Hi @natabal 
CSS fixed on variationTextGraph and table content font size. Please have a look.
[![Screenshot from Gyazo](https://gyazo.com/377129eb8863d1c063a6bd9e07c87b99/raw)](https://gyazo.com/377129eb8863d1c063a6bd9e07c87b99)
[![Screenshot from Gyazo](https://gyazo.com/a7922c3c85a87c1249e8de443c16a694/raw)](https://gyazo.com/a7922c3c85a87c1249e8de443c16a694)
[![Screenshot from Gyazo](https://gyazo.com/5556e9fbe5fce680a59b8fb91f3d2eeb/raw)](https://gyazo.com/5556e9fbe5fce680a59b8fb91f3d2eeb)

[css-bug]: fix variationTextGraph content rendering & table font-size issue

---

Graphs/Table/tableGraph.test.js

This fixes lint error during CI/CD in tableGraph tests that was causing `vsd-react-ui` build to fail.
```
/home/nn/projects/vsd-react-ui/src/lib/vis-graphs/Graphs/Table/tableGraph.test.js
8:1   error    Import in body of module; reorder to top    import/first
9:1   error    Import in body of module; reorder to top    import/first
```

fix import/first lint error in tableGraph test from upstream

---

Graphs/AbstractGraph.js
Graphs/PieGraph/default.config.js
Graphs/PieGraph/index.js
README.md

@natabal 
Issue #87 along with updated docs has been fixed.
Now use `labelCount: 5` to hide the labels if the data size is greater than 5. Default is 5.
You may override labelCount property.
There is one more property which will combine the smaller slices together after a certain count i.e 
`"otherOptions": {
"label": "Others",
"limit": 5,
"type": "number"
}`
It will show only 6 slices, 5 bigger slice and all the smaller one as just one slice named as "other". 
You can also change the number to percentage as well. You can refer to docs for furhter details.
Respective PR - https://github.com/nuagenetworks/vis-config/pull/25
Also, fixed the another issue for overlapping brush area with legends as shown in the given image: -
[![Screenshot from …

Fix slice color issue

---

Graphs/AbstractGraph.js

@natabal 
I debugged it and found that property **brushArea** is defined as **2**, i.e. 2% of the available width.
Therefore calculating the brush area after reducing margins, it is going in negative.
Now I have fixed the margin issue along with restricting the brush to the min of 10px width.
Please review.

Set min width for brush

---

Graphs/LineGraph/default.config.js
Graphs/LineGraph/index.js

@natabal 
Following bugs has been fixed in this PR - 
1) Spacing issue between Y label title and Y label ticks.
2) Calculate label size for manually defined `yTicksLabel` values.
Also, I have added `"yTicks": 5` to avoid collision among ticks. PR for the same is [#39](https://github.com/nuagenetworks/vis-config/pull/39)
You may also reduce the y tick font size by using the combination of `yTickFontSize` and `chartWidthToPixel` property. The default font size is `12` px (in number).

[bug]: y label title and ticks overlapping

---

Graphs/PieGraph/index.js
Graphs/defaultProperties.js
README.md

@natabal 
Added following properties for labels - 
`labelFontSize`:  change the font-size of labels. The default is 10px.
`labelLimit`: Add a limit to show label character, after the defined label character `...` is appended with a tooltip of full character for each label. The default limit is 10.

Add label setting properties

---

Graphs/AbstractGraph.js
Graphs/LineGraph/index.js
Graphs/XYGraph.js
Graphs/defaultProperties.js
README.md

@natabal 
Fixed percentage overflow issue in the y-axis.
Added the following properties to handle percentage overflow: -
- **zeroStart** (boolean) eg. if the value is from range say 30 to 89 and zeroStart is enabled, then this will change the range to 0 to 89. Default value of zeroStart is "true", and currently applicable for line and area graph.
- **yRangePadding** (boolean) default value is ```false```, if property is enabled then this will add padding around the min and max range, say min and max  range is 34 to 83, then this will change it to 30 to 90.

Percentage overflow in Y-Axis

---

Graphs/DynamicBarGraph/index.js
README.md
utils/helpers/barGraph/dataParser.js
utils/helpers/sorter.js

@natabal 
Added `stackSequence` property for sorting stacked data manually.
If you provide any value(s) in `stackSequence` array then it will come first in the stacked list and rest values will be sorted `asc/desc`  as provided by default. Please have a look.

Add custom sorting for stacked bar graph

---

Graphs/TreeGraph/default.config.js
Graphs/TreeGraph/index.js

There is attributesToShow key in topology.json config file where we added attributes to show based on contextName like for domain we will show name and description.
Similary the error was vminterface where no key added for this context name.
So I added attributes for vminterface and set the "default": { "name": true,"description": true} also if no context available in config file.

Added check to get default attributes name , description to show on rect node when no context name available

---

Graphs/TreeGraph/index.js

@bmukheja @natabal 
removed ui side dependency of treeGraph.Please have a look.
Dependent PR - https://github.com/nuagenetworks/vsd-react-ui/pull/2685

removed ui side dependency

---

Graphs/LineGraph/index.js
README.md
utils/columnAccessor.js

Fix duration time zone format issue #140. Please have a look.
Now you may set desired time format by using `duration` property in the tooltip instead of  the `timeFormat` property. E.g - 
`{ "column": "timestamp", "label": "Value", "duration": "h [hrs], m [min], s [sec]"}`
Note: update the readme docs.
Dependent PR - https://github.com/nuagenetworks/vsd-react-ui/pull/2681

[Bug]: Fix duartion format issue #140

---

Graphs/Table/index.js

- Table header row becomes fixed with this change
Sample:
Before:
After:

VSD-24399: fixed table header

---

Graphs/Table/index.js

This reverts commit 3232575270f16448235576a1785174012f357369
Noticed that fixedHeader prop causes column alignment issues. Hence reverting.
With fixedHeader:
Without fixedHeader:
Hence backing out the recent commit.

Revert "Merge pull request #164 from killanch/tableheader"

---

Graphs/ChordGraph/default.config.js
Graphs/ChordGraph/index.js
README.md

@nxanil @natabal  We have a scenario where tooltip content should show values corresponding to one direction only. Pls check if ok.
Config without bidirectionalTooltip property (default behavior):
Config with bidirectionalTooltip set to false:

Chordgraph - tooltip for only one direction

---

Graphs/SimpleTextGraph/default.config.js
Graphs/SimpleTextGraph/index.js
README.md

- Request from PLM to not show redundant title within text
- 'enableTitleInText' prop used to disable title
Sample:
Before:
After (with enableTitleInText set as false):

SimpleTextGraph - customText

---

Graphs/Table/index.js
README.md
SearchBar/AutoCompleteHandler.js

- react filter box expects `columnField`, but we were using `columField`, because of which search was not successful

VSD-35412 - fix columnField in table filter

---

Graphs/VariationTextGraph/default.config.js
Graphs/VariationTextGraph/index.js
Graphs/VariationTextGraph/styles.js
README.md

Sample: The visualization on the right uses showVariation false and absolute true,
This is to be used in one of the wifi visualizations.
I do not have a set up right now.

VariationTextGraph - config option to not display percentage

---

Graphs/ProgressBarGraph/index.js

Two changes,
1. data was being overwritten in getData() - use spread operator to deepclone
2. use units from data - let me know if this is ok, else I shall set MB as units in configuration, and update the tabify function in nsgDiskUsage.js to send values converted to MB
Sample:

ProgressBarGraph: do not update data, use unit from data

---

Graphs/AbstractGraph.js

- prevProps was not being used in check to determined if tooltip needs to be reinitialized

Graph - reinitialize tooltips when configuration.data changes

---

Graphs/AbstractGraph.js

Fix issue #178 by using 1st approach in this issue.
Now only non-empty values will display on tooltip. Please have a look.

Handle empty tooltip value  #178

---

Graphs/Table/index.js
README.md

@natabal 
Add the feature to display the table column dynamically.
To enable this feature, add the event listener (queryparams) key-value in the array of the column object (`displayOption`) in the setting as given below: 
`
"columns": [
{ "column": "gatewayName", "label": "NSG", "displayOption": {"app": "facebook", "nsg": "ovs-1"} },
{ "column": "address","totalCharacters":50, "label": "Address" },
]`
So, in above `displayOption` if any event listener has a value `app=facebook` or `nsg=ovs-1` then this column `gatewayName` will be displayed on the table.
Please let me know if I am missing anything.
Note: This PR is created from the base PR `fix-MUI-vulnerabilityIssue`
`

[feature]: add dynamic columns

---

Graphs/AreaGraph/index.js
Graphs/DynamicBarGraph/index.js
Graphs/HeatmapGraph/index.js
Graphs/LineGraph/index.js
Graphs/PieGraph/index.js
utils/helpers/barGraph/barWidth.js
utils/helpers/barGraph/dataParser.js
utils/helpers/index.js
utils/helpers/limit/limitIndex.js
utils/helpers/merge.js
utils/helpers/nest/nest.js
utils/helpers/nest/nestMinMaxSum.js
utils/helpers/nest/nestStack.js
utils/helpers/nest/nestSum.js
utils/helpers/reducers/reducerSumByKeys.js

It seems that we have circular dependencies in this lib:
```
1) utils/helpers/index.js > utils/helpers/barGraph/index.js > utils/helpers/barGraph/barWidth.js
2) utils/helpers/index.js > utils/helpers/barGraph/index.js > utils/helpers/barGraph/dataParser.js
3) utils/helpers/index.js > utils/helpers/limit/index.js > utils/helpers/limit/limit.js > utils/helpers/limit/limitIndex.js
4) utils/helpers/index.js > utils/helpers/limit/index.js > utils/helpers/limit/limit.js > utils/helpers/merge.js
5) utils/helpers/index.js > utils/helpers/nest/index.js > utils/helpers/nest/nest.js
6) utils/helpers/index.js > utils/helpers/nest/index.js > utils/helpers/nest/nestMinMaxSum.js
7) utils/helpers/index.js > utils/helpers/nest/index.js > utils/helpers/nest/nestStack.js
8) utils/helpers/index.js > …
```

Fix circular dependencies

---

GraphsV2/AreaGraph/index.js
GraphsV2/Components/utils/AreaTooltip.js
GraphsV2/Components/utils/Legend/StandardLegend.js

@natabal 
Fix issue #388. Please have a look.
Please use `lineColumn` in the visualization file like : 
**"linesColumn": ["LossAfterFEC", "NetworkLoss"],**

[Fix]: Area graph tooltip issue

---

Graphs/ProgressBarGraph/index.js

- Issue: numerical data from props was being wrongly transformed as string, because of which graph was not being rendered
- fix: ensure that same object from props is not manipulated
Sample:

fix VSD-50716 - progress graph data

---

Graphs/Table/index.js

- When value for a column is an object, Table rendering fails with below exception
```
Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {Client, doc_count, IP}). If you meant to render a collection of children, use an array instead.
in div (created by Grid)
in div (created by Grid)
in div (created by Grid)
in div (created by Grid)
in Grid (created by Table)
in div (created by Table)
in Table (at Table/index.js:668)
in div (created by AutoSizer)
in AutoSizer (at Table/index.js:665)
in InfiniteLoader (at Table/index.js:659)
in div (at Table/index.js:658)
in div (at Table/index.js:657)
in div (at Table/index.js:648)
```
- Fix: if object, then render null. this is on par with our r6.0 implementation

Table - fix exception when column data is object

---

Graphs/AbstractGraph.js
Graphs/AreaGraph/index.js
Graphs/Components/utils/Legend/StandardLegend.js
Graphs/Components/utils/Legend/index.js
Graphs/HeatmapGraph/index.js

@killanch  @chaitanyahalbe 
Fixed issue #434. Please review this PR.

[Feature]: Heatmap & AreaGraph Legends

---

Graphs/Table/index.js

- Addresses https://github.com/nuagenetworks/vis-graphs/issues/440
- disabled scroll-sorting on column if `"sort": false` specified in column configuration
- static-sorting allowed always

Table - disable scroll-sort on specific columns

---

Graphs/ChordGraph/Svg.js

**Issue:** There is no check for `onClick` prop passed on to the Svg component. `ChordGraph` component does not send `onClick` prop and hence there is an error when we click inside the `ChordGraph`. In dev environment the app crashes and in prod a console error is logged.
**Solution:** Add a check for onClick prop.

VSD-51747 onClick error when clicked inside graph area

---

Graphs/TreeGraph/index.js

Issue: Though `kids` within data gets changed, useEffect does not get triggered. This is because of data object shallow diff/comparison
Fix: Pass `kids` explicitly within second array param such that useEffect gets triggered if child nodes data changes
Also required vsd-react-ui change: https://github.com/nuagenetworks/vsd-react-ui/pull/4848
Before:
After:

VSD-51734 - tree view pagination

---

Graphs/PieGraph/index.js

Issue: If there is only one element in data array, array.reduce will not work unless initial value is provided. Because of this, value of `Total` is not a number
Fix: Set initial value as 0
Before:
After:

fix pie graph percentage tooltip

---

Graphs/Table/index.js

- fixes below error
```
TypeError: Cannot read property 'includes' of undefined
onRowClick
src/lib/vis-graphs/Graphs/Table/index.js:414
411 | 
412 | const onRowClick = ({ index }) => {
413 |     let selectedRowsCurr = rowSelected;
> 414 |     if (rowSelected.includes(index)) {
| ^  415 |         selectedRowsCurr = rowSelected.filter(item => item !== index);
416 |     } else {
417 |         selectedRowsCurr = !!multiSelectable ? [...selectedRowsCurr, index] : [index];
```
- if matching `requestId` not available in `selectedRows`, return empty array instead of undefined. this happens if filter value is changed by the user. `requestId` will change with filter value change

VSD-52408 - fix table error on row selection after filter change

---

Graphs/Table/index.js
Graphs/Table/style.js

Issue 2: Refresh icon is overlapping the UL list
Fix 2: Send a cutom style for refresh icon component and adjust the container' div's padding style. Make sure the refresh icon is on the right of the filterColumn dropdown if present
Issue 2: Before fix:
Issue 2: After fix
After fix with forced filteredColoumn

VSD-52348 - Reposition refresh icon in graphs

---

Graphs/Table/index.js

@shashank-nx
Fixed issue https://github.com/nuagenetworks/vis-graphs/issues/463. Please verify once.
@preshitg  
Please review the changes.

[Fix]: Table graph select column issue

---

Graphs/Components/utils/yAxis.js
Graphs/LineGraph/index.js

**Jira:** VSD-57649.
There is another pull request for vsd-react-ui side of fix: https://github.com/nuagenetworks/vsd-react-ui/pull/5455
Since the issue is on uplinkConnection context, I only put the transform data method on that page, so the other pages using metricsGraph and GraphView are not affected.

Fix VSD 57649 NSG - LTE uplink connection type and status in VSD-A are numeric
